version: '3.7'

services:
  node-app:
    build: .  # buduj obraz, jaki znajduje się tutaj w Dockerfile
    ports:
      - "9000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    #env_file:
    #  - ./.env
    


#docker-compose up -d    # uruchomi kontenery w tle